import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { motion } from "motion/react";
import { AlertTriangle, BarChart3, BellRing, CandlestickChart, ClipboardList, ExternalLink, LineChart, Lock, NotebookPen, Plus, Rss, Save, ShieldCheck, Target, Trash2 } from "lucide-react";
import { CandlestickSeries, ColorType, CrosshairMode, HistogramSeries, createChart, type CandlestickData, type HistogramData, type IChartApi, type ISeriesApi, type UTCTimestamp } from "lightweight-charts";
import { API, type AgentMapNode, type AgentMapResponse, type RssFeedItem, type RssFeedsResponse, type TradingWorkbenchResponse } from "../lib/api";
import { COMPOSED, staggerItem } from "../lib/motion";

type WorkRow = Record<string, unknown>;
type Timeframe = "1H" | "4H" | "1D" | "1W";
type Plan = { account: number; risk_pct: number; entry: number; stop: number; target: number };

const TIMEFRAMES: Timeframe[] = ["1H", "4H", "1D", "1W"];
const STARTER = ["SPY", "QQQ", "BTCUSD", "ETHUSD", "NVDA", "TSLA"];
const FOCUS = new Set(["markets", "macro", "watchlist", "technical-analysis", "trading-video"]);
const panel = { border: "1px solid var(--s-edge-subtle)", background: "var(--s-glass-light)" };
const field = { background: "var(--s-glass)", border: "1px solid var(--s-edge-subtle)", color: "var(--s-text-primary)" };
const quiet = { color: "var(--s-text-secondary)", fontSize: "var(--t-11)" };

function statusColor(status: string): string {
  if (status === "live" || status === "working") return "var(--s-status-ok)";
  if (status === "blocked") return "var(--s-status-warn)";
  if (status === "error") return "var(--s-status-error)";
  return "var(--s-text-secondary)";
}
function text(value: unknown): string { return String(value || ""); }
function num(value: unknown, fallback = 0): number { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
function tf(value: unknown): Timeframe { const raw = String(value || "1D").toUpperCase(); return TIMEFRAMES.includes(raw as Timeframe) ? raw as Timeframe : "1D"; }
function plan(raw: unknown): Plan {
  const v = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
  return { account: num(v.account, 10000), risk_pct: num(v.risk_pct, 1), entry: num(v.entry), stop: num(v.stop), target: num(v.target) };
}
function emptyWorkbench(): TradingWorkbenchResponse {
  return { ok: true, active_symbol: "SPY", timeframe: "1D", position_plan: { account: 10000, risk_pct: 1, entry: 0, stop: 0, target: 0 }, watchlist: STARTER, alerts: [], risk_rules: [], research_queue: [], journal: [] };
}
function mergeWorkbench(next: TradingWorkbenchResponse): TradingWorkbenchResponse {
  const watchlist = Array.from(new Set([...(next.watchlist || []), ...(!next.watchlist?.length ? STARTER : [])].map((s) => String(s).toUpperCase()).filter(Boolean)));
  return { ...emptyWorkbench(), ...next, watchlist, active_symbol: String(next.active_symbol || watchlist[0] || "SPY").toUpperCase(), timeframe: tf(next.timeframe), position_plan: plan(next.position_plan), alerts: next.alerts || [], risk_rules: next.risk_rules || [], research_queue: next.research_queue || [], journal: next.journal || [] };
}
function seedFor(symbol: string, frame: Timeframe): number { let seed = 2166136261; for (const ch of `${symbol}:${frame}`) { seed ^= ch.charCodeAt(0); seed = Math.imul(seed, 16777619); } return seed >>> 0; }
function rng(seed: number): () => number { let s = seed || 1; return () => { s = Math.imul(1664525, s) + 1013904223; return (s >>> 0) / 4294967296; }; }
function seconds(frame: Timeframe): number { return frame === "1H" ? 3600 : frame === "4H" ? 14400 : frame === "1W" ? 604800 : 86400; }
function basePrice(symbol: string): number { if (symbol.includes("BTC")) return 64000; if (symbol.includes("ETH")) return 3400; if (symbol === "SPY") return 540; if (symbol === "QQQ") return 470; if (symbol === "NVDA") return 128; if (symbol === "TSLA") return 190; return 80 + (seedFor(symbol, "1D") % 260); }
function makeSeries(symbol: string, frame: Timeframe): { candles: CandlestickData[]; volumes: HistogramData[]; last: number; changePct: number } {
  const r = rng(seedFor(symbol, frame)); const count = frame === "1H" ? 160 : frame === "4H" ? 150 : frame === "1W" ? 120 : 180; const step = seconds(frame); const now = Math.floor(Date.now() / 1000 / step) * step;
  let close = basePrice(symbol) * (0.92 + r() * 0.18); const candles: CandlestickData[] = []; const volumes: HistogramData[] = [];
  for (let i = count - 1; i >= 0; i -= 1) { const time = (now - i * step) as UTCTimestamp; const drift = (r() - 0.48) * (frame === "1H" ? 0.012 : frame === "4H" ? 0.018 : 0.026); const open = close; close = Math.max(0.01, open * (1 + drift)); const spread = Math.max(open, close) * (0.004 + r() * 0.022); const high = Math.max(open, close) + spread; const low = Math.max(0.01, Math.min(open, close) - spread * (0.8 + r() * 0.4)); candles.push({ time, open, high, low, close }); volumes.push({ time, value: Math.round((850000 + r() * 6500000) * (symbol.includes("BTC") || symbol.includes("ETH") ? 0.35 : 1)), color: close >= open ? "rgba(45,212,191,0.32)" : "rgba(248,81,73,0.32)" }); }
  const first = candles[0]?.close || close; const last = candles[candles.length - 1]?.close || close; return { candles, volumes, last, changePct: first ? ((last - first) / first) * 100 : 0 };
}
function money(value: number): string { return Number.isFinite(value) ? value.toLocaleString(undefined, { style: "currency", currency: "USD", maximumFractionDigits: value > 1000 ? 0 : 2 }) : "$0.00"; }
function fmt(value: number, digits = 2): string { return Number.isFinite(value) ? value.toLocaleString(undefined, { maximumFractionDigits: digits }) : "0"; }

function Panel({ title, icon, action, children }: { title: string; icon?: ReactNode; action?: ReactNode; children: ReactNode }) {
  return <section className="min-w-0 rounded-lg" style={panel}><div className="flex min-h-12 items-center justify-between gap-3 px-4 py-3" style={{ borderBottom: "1px solid var(--s-edge-subtle)" }}><div className="flex min-w-0 items-center gap-2" style={{ color: "var(--s-text-primary)", fontWeight: 750 }}>{icon}<span className="truncate">{title}</span></div>{action}</div>{children}</section>;
}
function Metric({ icon, value, label }: { icon: ReactNode; value: string | number; label: string }) {
  return <div className="rounded-lg p-4" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }}>{icon}<div className="mt-3" style={{ color: "var(--s-text-primary)", fontSize: "var(--t-20)", fontWeight: 780 }}>{value}</div><div style={{ color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>{label}</div></div>;
}
function MarketChart({ symbol, frame }: { symbol: string; frame: Timeframe }) {
  const hostRef = useRef<HTMLDivElement | null>(null); const chartRef = useRef<IChartApi | null>(null); const candleRef = useRef<ISeriesApi<"Candlestick"> | null>(null); const volumeRef = useRef<ISeriesApi<"Histogram"> | null>(null); const data = useMemo(() => makeSeries(symbol, frame), [symbol, frame]);
  useEffect(() => { const host = hostRef.current; if (!host) return; const chart = createChart(host, { width: Math.max(320, host.clientWidth), height: Math.max(360, host.clientHeight), layout: { background: { type: ColorType.Solid, color: "rgba(6,12,16,0.08)" }, textColor: "rgba(226,238,234,0.76)", fontFamily: "var(--font-mono)" }, grid: { vertLines: { color: "rgba(122,199,167,0.08)" }, horzLines: { color: "rgba(122,199,167,0.08)" } }, crosshair: { mode: CrosshairMode.Normal }, rightPriceScale: { borderColor: "rgba(122,199,167,0.18)", scaleMargins: { top: 0.08, bottom: 0.24 } }, timeScale: { borderColor: "rgba(122,199,167,0.18)", timeVisible: frame === "1H" || frame === "4H" }, handleScroll: true, handleScale: true }); const candleSeries = chart.addSeries(CandlestickSeries, { upColor: "#2dd4bf", downColor: "#f85149", borderUpColor: "#7ac7a7", borderDownColor: "#f85149", wickUpColor: "#7ac7a7", wickDownColor: "#f85149" }); const volumeSeries = chart.addSeries(HistogramSeries, { priceFormat: { type: "volume" }, priceScaleId: "volume" }); chart.priceScale("volume").applyOptions({ scaleMargins: { top: 0.78, bottom: 0 } }); chartRef.current = chart; candleRef.current = candleSeries; volumeRef.current = volumeSeries; const ro = new ResizeObserver(([entry]) => chart.applyOptions({ width: Math.max(320, Math.floor(entry.contentRect.width)), height: Math.max(360, Math.floor(entry.contentRect.height)) })); ro.observe(host); return () => { ro.disconnect(); chart.remove(); chartRef.current = null; candleRef.current = null; volumeRef.current = null; }; }, [frame]);
  useEffect(() => { candleRef.current?.setData(data.candles); volumeRef.current?.setData(data.volumes); chartRef.current?.timeScale().fitContent(); }, [data]);
  return <div className="relative min-h-[420px] overflow-hidden rounded-lg" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(5,10,13,0.62)" }}><div className="absolute left-3 top-3 z-10 flex flex-wrap items-center gap-2"><span className="rounded-lg px-2.5 py-1" style={{ border: "1px solid rgba(20,156,150,0.36)", background: "rgba(6,18,20,0.78)", color: "var(--s-text-primary)", fontWeight: 760 }}>{symbol}</span><span className="rounded-lg px-2.5 py-1" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(6,18,20,0.74)", color: data.changePct >= 0 ? "var(--s-status-ok)" : "var(--s-status-error)", fontFamily: "var(--font-mono)", fontSize: "var(--t-12)" }}>{money(data.last)} {data.changePct >= 0 ? "+" : ""}{data.changePct.toFixed(2)}%</span></div><div ref={hostRef} data-servari-trading-chart="true" className="h-[420px] w-full" /></div>;
}
function SignalRow({ item, index, onQueue }: { item: RssFeedItem; index: number; onQueue: (item: RssFeedItem) => void }) {
  return <motion.div className="grid gap-2 rounded-lg px-3 py-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }} {...staggerItem(index)}><div className="flex items-center justify-between gap-3"><span className="truncate" style={{ color: "var(--s-text-teal-soft)", fontSize: "var(--t-11)", fontFamily: "var(--font-mono)" }}>{item.source || item.category || "feed"}</span><Rss size={13} style={{ color: "var(--s-text-secondary)" }} /></div><a href={item.url || undefined} target={item.url ? "_blank" : undefined} rel="noreferrer" className="line-clamp-2" style={{ color: "var(--s-text-primary)", fontSize: "var(--t-13)", lineHeight: 1.4, fontWeight: 650 }}>{item.title}</a><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => onQueue(item)} className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)", fontSize: "var(--t-11)" }}><Plus size={13} />Research</button>{item.url && <a href={item.url} target="_blank" rel="noreferrer" className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid var(--s-edge-subtle)", color: "var(--s-text-secondary)", background: "rgba(250,248,243,0.025)", fontSize: "var(--t-11)" }}><ExternalLink size={13} />Open</a>}</div></motion.div>;
}
function AgentRow({ agent, index }: { agent: AgentMapNode; index: number }) {
  return <motion.div className="grid grid-cols-[auto_1fr_auto] items-center gap-3 px-3 py-2" style={{ borderBottom: "1px solid var(--s-edge-subtle)" }} {...staggerItem(index)}><span className="h-2.5 w-2.5 rounded-full" style={{ background: statusColor(agent.status), boxShadow: agent.status === "working" ? "var(--s-glow-green)" : "none" }} /><div className="min-w-0"><div className="truncate" style={{ color: "var(--s-text-primary)", fontSize: "var(--t-12)", fontWeight: 700 }}>{agent.name}</div><div className="truncate" style={{ color: "var(--s-text-secondary)", fontSize: "var(--t-11)" }}>{agent.role} / {agent.runtime_backend || "backend"}</div></div><span style={{ color: "var(--s-text-secondary)", fontFamily: "var(--font-mono)", fontSize: "var(--t-11)" }}>{agent.turns}t</span></motion.div>;
}

export function TradingDesk() {
  const [map, setMap] = useState<AgentMapResponse | null>(null); const [feeds, setFeeds] = useState<RssFeedsResponse | null>(null); const [workbench, setWorkbench] = useState<TradingWorkbenchResponse>(() => emptyWorkbench()); const [symbol, setSymbol] = useState(""); const [filter, setFilter] = useState("all"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const active = String(workbench.active_symbol || workbench.watchlist[0] || "SPY").toUpperCase(); const frame = tf(workbench.timeframe); const p = plan(workbench.position_plan); const market = useMemo(() => makeSeries(active, frame), [active, frame]);
  const load = useCallback(async () => { const [nextMap, nextFeeds, nextWorkbench] = await Promise.all([API.agentMap().catch(() => null), API.rssFeeds().catch(() => null), API.tradingWorkbench().catch(() => emptyWorkbench())]); if (nextMap) setMap(nextMap); if (nextFeeds) setFeeds(nextFeeds); setWorkbench(mergeWorkbench(nextWorkbench)); }, []);
  useEffect(() => { void load(); }, [load]);
  const tradingAgents = useMemo(() => (map?.agents || []).filter((agent) => agent.group === "trading"), [map]);
  const feedItems = useMemo(() => (feeds?.items || []).filter((item) => { const c = String(item.category || "").toLowerCase(); if (filter === "all") return FOCUS.has(c) || item.source?.toLowerCase().includes("capital") || item.source?.toLowerCase().includes("markets"); return c === filter; }).slice(0, 18), [feeds, filter]);
  const categories = useMemo(() => Array.from(new Set((feeds?.items || []).map((item) => String(item.category || "").toLowerCase()).filter(Boolean))).slice(0, 12), [feeds]);
  const riskBudget = Math.max(0, p.account * (p.risk_pct / 100)); const unitRisk = Math.abs(p.entry - p.stop); const size = unitRisk > 0 ? riskBudget / unitRisk : 0; const rr = unitRisk > 0 ? Math.abs(p.target - p.entry) / unitRisk : 0;
  const patch = useCallback((next: Partial<TradingWorkbenchResponse>) => setWorkbench((current) => ({ ...current, ...next })), []);
  const patchPlan = useCallback((next: Partial<Plan>) => setWorkbench((current) => ({ ...current, position_plan: { ...plan(current.position_plan), ...next } })), []);
  const save = useCallback(async () => { setSaving(true); setMessage(""); try { const next = await API.saveTradingWorkbench(workbench); setWorkbench(mergeWorkbench(next)); setMessage("Trading workbench saved."); } catch (error) { setMessage(`Save failed: ${error instanceof Error ? error.message : String(error)}`); } finally { setSaving(false); } }, [workbench]);
  const addSymbol = useCallback(() => { const clean = symbol.trim().toUpperCase().replace(/[^A-Z0-9.:-]/g, ""); if (!clean) return; setWorkbench((current) => ({ ...current, active_symbol: clean, watchlist: Array.from(new Set([clean, ...current.watchlist])) })); setSymbol(""); }, [symbol]);
  const removeSymbol = useCallback((item: string) => setWorkbench((current) => { const list = current.watchlist.filter((s) => s !== item); return { ...current, watchlist: list, active_symbol: current.active_symbol === item ? list[0] || "SPY" : current.active_symbol }; }), []);
  const queueSignal = useCallback((item: RssFeedItem) => setWorkbench((current) => ({ ...current, research_queue: [{ title: item.title, source: item.source || item.category || "RSS", url: item.url || "", status: "new", notes: String(item.category || "").toLowerCase() === "trading-video" ? "Video research: extract setup, catalyst, risk rule, invalidation, and repeatable checklist." : "" }, ...current.research_queue].slice(0, 200) })), []);
  const updateRow = useCallback((key: "alerts" | "risk_rules" | "journal", index: number, next: WorkRow) => setWorkbench((current) => ({ ...current, [key]: current[key].map((row, idx) => idx === index ? { ...row, ...next } : row) })), []);
  const removeRow = useCallback((key: "alerts" | "risk_rules" | "research_queue" | "journal", index: number) => setWorkbench((current) => ({ ...current, [key]: current[key].filter((_, idx) => idx !== index) })), []);
  const fillPlan = useCallback(() => { const entry = Number(market.last.toFixed(active.includes("BTC") || active.includes("ETH") ? 0 : 2)); patchPlan({ entry, stop: Number((entry * 0.98).toFixed(2)), target: Number((entry * 1.04).toFixed(2)) }); }, [active, market.last, patchPlan]);

  return <div className="h-full overflow-auto p-4 md:p-6 xl:p-8"><div className="mx-auto max-w-[1600px] space-y-4 pb-16"><motion.header className="flex flex-col gap-3 rounded-lg px-4 py-4 lg:flex-row lg:items-center lg:justify-between" style={{ border: "1px solid var(--s-edge-accent)", background: "var(--s-glass-light)" }} initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={COMPOSED}><div className="min-w-0"><div className="mb-1 flex items-center gap-2" style={{ color: "var(--s-text-teal)", fontSize: "var(--t-11)", letterSpacing: "var(--ls-caps)", textTransform: "uppercase" }}><BarChart3 size={15} />Trading Desk</div><h1 className="truncate" style={{ color: "var(--s-text-primary)", fontSize: "var(--t-24)", fontWeight: 780, letterSpacing: 0 }}>Chart, feeds, research, alerts, and risk plan</h1></div><div className="flex flex-wrap gap-2"><span className="inline-flex h-10 items-center gap-2 rounded-lg px-3" style={{ border: "1px solid rgba(224,169,42,0.36)", color: "var(--s-status-warn)", background: "rgba(224,169,42,0.08)", fontSize: "var(--t-12)" }}><AlertTriangle size={14} />Research only</span><button disabled className="inline-flex h-10 items-center gap-2 rounded-lg px-3 opacity-60" style={{ border: "1px solid var(--s-edge-subtle)", color: "var(--s-text-secondary)", background: "rgba(250,248,243,0.025)" }}><Lock size={14} />Broker execution locked</button><button type="button" onClick={() => void save()} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-lg px-3 disabled:opacity-50" style={{ border: "1px solid rgba(20,156,150,0.45)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.10)" }}><Save size={15} />{saving ? "Saving" : "Save"}</button></div></motion.header>{message && <div className="rounded-lg px-3 py-2" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)", color: message.includes("failed") ? "var(--s-status-error)" : "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>{message}</div>}

  <div className="grid gap-3 md:grid-cols-4"><Metric icon={<LineChart size={18} style={{ color: "var(--s-text-teal)" }} />} value={workbench.watchlist.length} label="watchlist symbols" /><Metric icon={<Rss size={18} style={{ color: "var(--s-text-teal)" }} />} value={feedItems.length} label="current signals" /><Metric icon={<BellRing size={18} style={{ color: "var(--s-status-warn)" }} />} value={workbench.alerts.length} label="armed alerts" /><Metric icon={<ShieldCheck size={18} style={{ color: "var(--s-status-ok)" }} />} value={workbench.risk_rules.length} label="risk rules" /></div>

  <div className="grid gap-4 xl:grid-cols-[minmax(280px,0.72fr)_minmax(520px,1.45fr)_minmax(320px,0.83fr)]"><Panel title="Watchlist & Agents" icon={<CandlestickChart size={16} style={{ color: "var(--s-text-teal)" }} />}><div className="grid gap-3 p-3"><div className="flex gap-2"><input value={symbol} onChange={(event) => setSymbol(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addSymbol(); }} placeholder="Symbol" className="min-w-0 flex-1 rounded-lg px-3 py-2 outline-none" style={field} /><button type="button" onClick={addSymbol} className="grid h-10 w-10 place-items-center rounded-lg" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)" }}><Plus size={15} /></button></div><div className="flex max-h-28 flex-wrap gap-2 overflow-auto pr-1">{workbench.watchlist.map((item) => <button key={item} type="button" onClick={() => patch({ active_symbol: item })} className="group inline-flex items-center gap-2 rounded-full px-2.5 py-1" style={{ border: item === active ? "1px solid rgba(20,156,150,0.58)" : "1px solid var(--s-edge-subtle)", color: item === active ? "var(--s-text-teal)" : "var(--s-text-primary)", background: item === active ? "rgba(20,156,150,0.10)" : "rgba(250,248,243,0.03)", fontSize: "var(--t-11)" }}>{item}<span role="button" tabIndex={0} onClick={(event) => { event.stopPropagation(); removeSymbol(item); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); event.stopPropagation(); removeSymbol(item); } }} className="grid h-4 w-4 place-items-center rounded-full opacity-70 group-hover:opacity-100" title={`Remove ${item}`}><Trash2 size={11} /></span></button>)}</div></div><div className="max-h-[300px] overflow-auto" style={{ borderTop: "1px solid var(--s-edge-subtle)" }}>{tradingAgents.map((agent, index) => <AgentRow key={agent.id} agent={agent} index={index} />)}{!tradingAgents.length && <div className="px-4 py-8 text-center" style={{ color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>No trading agents registered.</div>}</div></Panel>
  <Panel title={`${active} Market Chart`} icon={<LineChart size={16} style={{ color: "var(--s-text-teal)" }} />} action={<div className="flex flex-wrap gap-1">{TIMEFRAMES.map((item) => <button key={item} type="button" onClick={() => patch({ timeframe: item })} className="h-8 rounded-lg px-2" style={{ border: item === frame ? "1px solid rgba(20,156,150,0.56)" : "1px solid var(--s-edge-subtle)", color: item === frame ? "var(--s-text-teal)" : "var(--s-text-secondary)", background: item === frame ? "rgba(20,156,150,0.10)" : "rgba(250,248,243,0.025)", fontSize: "var(--t-11)", fontFamily: "var(--font-mono)" }}>{item}</button>)}</div>}><div className="p-3"><MarketChart symbol={active} frame={frame} /></div></Panel>
  <Panel title="Position Plan" icon={<Target size={16} style={{ color: "var(--s-text-teal)" }} />} action={<button type="button" onClick={fillPlan} className="h-8 rounded-lg px-2" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)", fontSize: "var(--t-11)" }}>Use last</button>}><div className="grid gap-3 p-3"><div className="grid grid-cols-2 gap-2">{([["Account", "account", 1], ["Risk %", "risk_pct", 0.1], ["Entry", "entry", 0.01], ["Stop", "stop", 0.01], ["Target", "target", 0.01]] as const).map(([label, key, step]) => <label key={key} className={key === "target" ? "col-span-2 grid gap-1" : "grid gap-1"}><span style={quiet}>{label}</span><input type="number" step={step} value={p[key]} onChange={(event) => patchPlan({ [key]: num(event.target.value) })} className="rounded-lg px-3 py-2 outline-none" style={field} /></label>)}</div><div className="grid grid-cols-2 gap-2">{[["Risk budget", money(riskBudget)], ["Unit risk", money(unitRisk)], ["Size", fmt(size, 4)], ["Reward/risk", `${fmt(rr, 2)}R`]].map(([label, value]) => <div key={label} className="rounded-lg p-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }}><div style={quiet}>{label}</div><div style={{ color: label === "Reward/risk" && rr >= 2 ? "var(--s-status-ok)" : "var(--s-text-primary)", fontWeight: 760 }}>{value}</div></div>)}</div></div></Panel></div>

  <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]"><Panel title="Signals Feed" icon={<Rss size={16} style={{ color: "var(--s-text-teal)" }} />} action={<select value={filter} onChange={(event) => setFilter(event.target.value)} className="h-9 rounded-lg px-3 outline-none" style={{ ...field, fontSize: "var(--t-12)" }}><option value="all">Trading focus</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select>}><div className="grid max-h-[470px] gap-2 overflow-auto p-3 md:grid-cols-2">{feedItems.map((item, index) => <SignalRow key={item.id || `${item.title}-${index}`} item={item} index={index} onQueue={queueSignal} />)}{!feedItems.length && <div className="rounded-lg px-3 py-8 text-center" style={{ border: "1px dashed var(--s-edge-subtle)", color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>No trading signals for this filter.</div>}</div></Panel>
  <Panel title="Research Queue" icon={<ClipboardList size={16} style={{ color: "var(--s-text-teal)" }} />}><div className="max-h-[470px] space-y-2 overflow-auto p-3">{workbench.research_queue.map((row, index) => <motion.div key={`${text(row.title)}-${index}`} className="grid gap-2 rounded-lg p-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }} {...staggerItem(index)}><div className="line-clamp-2" style={{ color: "var(--s-text-primary)", fontSize: "var(--t-12)", fontWeight: 700 }}>{text(row.title) || "Untitled research item"}</div><div style={quiet}>{text(row.source)}</div><textarea value={text(row.notes)} onChange={(event) => setWorkbench((current) => ({ ...current, research_queue: current.research_queue.map((item, idx) => idx === index ? { ...item, notes: event.target.value } : item) }))} placeholder="Setup, catalyst, invalidation, risk, checklist" className="min-h-[76px] resize-none rounded-lg px-3 py-2 outline-none" style={field} /><button type="button" onClick={() => removeRow("research_queue", index)} className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid rgba(248,81,73,0.28)", color: "var(--s-status-error)", background: "rgba(248,81,73,0.06)", fontSize: "var(--t-11)" }}><Trash2 size={13} />Remove</button></motion.div>)}{!workbench.research_queue.length && <div className="rounded-lg px-3 py-8 text-center" style={{ border: "1px dashed var(--s-edge-subtle)", color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>Queue an RSS or YouTube signal to start research.</div>}</div></Panel></div>

  <div className="grid gap-4 xl:grid-cols-3"><Panel title="Risk Rules" action={<button type="button" onClick={() => setWorkbench((current) => ({ ...current, risk_rules: [{ rule: "", limit: "", status: "active" }, ...current.risk_rules] }))} className="grid h-8 w-8 place-items-center rounded-lg" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)" }}><Plus size={14} /></button>}><div className="space-y-2 p-3">{workbench.risk_rules.map((rule, index) => <div key={index} className="grid gap-2 rounded-lg p-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }}><input value={text(rule.rule)} onChange={(event) => updateRow("risk_rules", index, { rule: event.target.value })} placeholder="Rule" className="rounded-lg px-3 py-2 outline-none" style={field} /><input value={text(rule.limit)} onChange={(event) => updateRow("risk_rules", index, { limit: event.target.value })} placeholder="Limit or gate" className="rounded-lg px-3 py-2 outline-none" style={field} /><button type="button" onClick={() => removeRow("risk_rules", index)} className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid rgba(248,81,73,0.28)", color: "var(--s-status-error)", background: "rgba(248,81,73,0.06)", fontSize: "var(--t-11)" }}><Trash2 size={13} />Remove</button></div>)}</div></Panel>
  <Panel title="Alert Rules" action={<button type="button" onClick={() => setWorkbench((current) => ({ ...current, alerts: [{ symbol: active, condition: "", channel: "desktop", status: "armed" }, ...current.alerts] }))} className="grid h-8 w-8 place-items-center rounded-lg" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)" }}><Plus size={14} /></button>}><div className="space-y-2 p-3">{workbench.alerts.map((alert, index) => <div key={index} className="grid gap-2 rounded-lg p-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }}><div className="grid gap-2 md:grid-cols-2"><input value={text(alert.symbol)} onChange={(event) => updateRow("alerts", index, { symbol: event.target.value.toUpperCase() })} placeholder="Symbol" className="rounded-lg px-3 py-2 outline-none" style={field} /><input value={text(alert.channel) || "desktop"} onChange={(event) => updateRow("alerts", index, { channel: event.target.value })} placeholder="Channel" className="rounded-lg px-3 py-2 outline-none" style={field} /></div><input value={text(alert.condition)} onChange={(event) => updateRow("alerts", index, { condition: event.target.value })} placeholder="Condition" className="rounded-lg px-3 py-2 outline-none" style={field} /><button type="button" onClick={() => removeRow("alerts", index)} className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid rgba(248,81,73,0.28)", color: "var(--s-status-error)", background: "rgba(248,81,73,0.06)", fontSize: "var(--t-11)" }}><Trash2 size={13} />Remove</button></div>)}{!workbench.alerts.length && <div className="rounded-lg px-3 py-6 text-center" style={{ border: "1px dashed var(--s-edge-subtle)", color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>No alert rules configured.</div>}</div></Panel>
  <Panel title="Journal" icon={<NotebookPen size={16} style={{ color: "var(--s-text-teal)" }} />} action={<button type="button" onClick={() => setWorkbench((current) => ({ ...current, journal: [{ ts: new Date().toISOString(), symbol: active, note: "", tags: "" }, ...current.journal] }))} className="grid h-8 w-8 place-items-center rounded-lg" style={{ border: "1px solid rgba(20,156,150,0.35)", color: "var(--s-text-teal)", background: "rgba(20,156,150,0.08)" }}><Plus size={14} /></button>}><div className="space-y-2 p-3">{workbench.journal.map((entry, index) => <div key={index} className="grid gap-2 rounded-lg p-3" style={{ border: "1px solid var(--s-edge-subtle)", background: "rgba(250,248,243,0.025)" }}><textarea value={text(entry.note)} onChange={(event) => updateRow("journal", index, { note: event.target.value })} placeholder="Decision, thesis, invalidation, lesson" className="min-h-[108px] resize-none rounded-lg px-3 py-2 outline-none" style={field} /><input value={text(entry.tags)} onChange={(event) => updateRow("journal", index, { tags: event.target.value })} placeholder="tags" className="rounded-lg px-3 py-2 outline-none" style={field} /><button type="button" onClick={() => removeRow("journal", index)} className="inline-flex h-8 w-fit items-center gap-2 rounded-lg px-2" style={{ border: "1px solid rgba(248,81,73,0.28)", color: "var(--s-status-error)", background: "rgba(248,81,73,0.06)", fontSize: "var(--t-11)" }}><Trash2 size={13} />Remove</button></div>)}{!workbench.journal.length && <div className="rounded-lg px-3 py-6 text-center" style={{ border: "1px dashed var(--s-edge-subtle)", color: "var(--s-text-secondary)", fontSize: "var(--t-12)" }}>No journal notes yet.</div>}</div></Panel></div>
</div></div>;
}

export default TradingDesk;
